# Generated by Django 3.0.3 on 2021-12-26 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitEveryDayNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='通过后台自动计算的按照日期聚合访问次数', verbose_name='统计日期')),
                ('visit_count', models.IntegerField(default=0, help_text='当日网站访问总次数', verbose_name='统计次数')),
            ],
            options={
                'verbose_name': '网站日访问量统计',
                'verbose_name_plural': '网站日访问量统计',
            },
        ),
        migrations.CreateModel(
            name='VisitEveryIpCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_ip', models.CharField(help_text='访问网站的IP地址信息记录', max_length=30, verbose_name='IP地址')),
                ('visit_count', models.IntegerField(default=0, help_text='通过后台自动计算的IP聚合访问次数', verbose_name='IP访问次数')),
            ],
            options={
                'verbose_name': 'IP访问汇总',
                'verbose_name_plural': 'IP访问汇总',
            },
        ),
        migrations.CreateModel(
            name='VisitIpPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_ip', models.CharField(help_text='访问网站的IP地址信息记录', max_length=30, verbose_name='IP地址')),
                ('visit_address', models.CharField(max_length=100, verbose_name='访问IP地区')),
                ('visit_part', models.CharField(help_text='访问网站的具体内容模块', max_length=30, verbose_name='内容模块')),
                ('visit_time', models.DateTimeField(default=django.utils.timezone.now, help_text='默认创建时系统时间', verbose_name='访问时间')),
            ],
            options={
                'verbose_name': 'IP访问明细',
                'verbose_name_plural': 'IP访问明细',
            },
        ),
        migrations.CreateModel(
            name='VisitTotalNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_count', models.IntegerField(default=0, help_text='统计的网站被访问的总次数', verbose_name='网站访问总次数')),
            ],
            options={
                'verbose_name': '网站访问总次数',
                'verbose_name_plural': '网站访问总次数',
            },
        ),
    ]
