# Generated by Django 3.0.3 on 2021-12-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfav',
            old_name='article_slug',
            new_name='info_slug',
        ),
        migrations.RenameField(
            model_name='userorder',
            old_name='article_slug',
            new_name='info_slug',
        ),
        migrations.RenameField(
            model_name='userread',
            old_name='article_slug',
            new_name='info_slug',
        ),
        migrations.RenameField(
            model_name='usershare',
            old_name='article_slug',
            new_name='info_slug',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='actual_name',
            field=models.CharField(blank=True, help_text='真实姓名', max_length=10, null=True, verbose_name='用户姓名'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, default='', help_text='地址信息', max_length=100, verbose_name='联系地址'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, help_text='生日', null=True, verbose_name='用户生日'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Male', '男性'), ('Female', '女性'), ('Undefined', '未定义')], default='未定义', help_text='性别', max_length=9, verbose_name='用户性别'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='integral',
            field=models.IntegerField(default=0, help_text='积分', verbose_name='用户积分'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, help_text='移动电话', max_length=11, null=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nick_name',
            field=models.CharField(blank=True, help_text='昵称', max_length=20, null=True, verbose_name='用户昵称'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(blank=True, default='UserImage/default.png', help_text='头像图片', null=True, upload_to='UserImage', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_role',
            field=models.CharField(choices=[('Root', '超级管理员'), ('EditUser', '编辑'), ('ReviewUser', '审核'), ('WebsiteUsers', '网站用户'), ('Tourist', '游客')], default='游客', help_text='角色', max_length=20, verbose_name='用户角色'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='vip_exp',
            field=models.IntegerField(default=0, help_text='经验值', verbose_name='用户经验'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='vip_level',
            field=models.IntegerField(default=0, help_text='等级', verbose_name='用户等级'),
        ),
        migrations.AlterUniqueTogether(
            name='userfav',
            unique_together={('user', 'info_slug')},
        ),
        migrations.AlterUniqueTogether(
            name='userread',
            unique_together={('user', 'info_slug', 'add_time')},
        ),
    ]
