# Generated by Django 3.0.3 on 2021-12-26 18:20

import DjangoUeditor.models
import apps.Configuration.config_choose
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', '未审核'), ('1', '已审核'), ('2', '审核不通过')], default=1, help_text='默认未审核', max_length=1, verbose_name='使用状态')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='使用默认的系统时间', verbose_name='数据创建时间')),
                ('name', models.CharField(help_text='最多使用30个字符', max_length=30, verbose_name='大类名称')),
            ],
            options={
                'verbose_name': '文章大类管理',
                'verbose_name_plural': '文章大类管理',
            },
        ),
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('detail_slug', models.SlugField(default=apps.Configuration.config_choose.default_time, help_text='自动按时间戳生成', primary_key=True, serialize=False, verbose_name='文章slug')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='内容正文')),
            ],
            options={
                'verbose_name': '文章详情管理',
                'verbose_name_plural': '文章详情管理',
            },
        ),
        migrations.CreateModel(
            name='ArticleInfo',
            fields=[
                ('status', models.CharField(choices=[('0', '未审核'), ('1', '已审核'), ('2', '审核不通过')], default=0, help_text='默认未审核,超级用户和编辑有权限审核', max_length=1, verbose_name='使用状态')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='使用默认的系统时间', verbose_name='数据创建时间')),
                ('home_position', models.CharField(choices=[('0', '非首页显示'), ('1', '最新内容'), ('2', '热门内容'), ('3', '浏览最多'), ('4', '转发最多'), ('5', '收藏最多'), ('6', '内容滚动推荐'), ('7', '大图置顶轮播')], default=0, help_text='默认非主页显示,若没有请在config_choose中添加', max_length=1, verbose_name='文章位置')),
                ('item_position', models.CharField(choices=[('0', '栏目中不显示'), ('1', '栏目中显示数据')], default=0, help_text='默认栏目中不显示,若没有请在config_choose中添加', max_length=1, verbose_name='栏目列表是否可见')),
                ('title', models.CharField(default='', help_text='最多使用100个字符', max_length=100, verbose_name='文章标题')),
                ('info_slug', models.SlugField(default=apps.Configuration.config_choose.default_time, help_text='自动按时间戳生成', primary_key=True, serialize=False, verbose_name='文章slug')),
                ('ai_type', models.CharField(blank=True, help_text='最多使用20个字符，可以为空', max_length=20, null=True, verbose_name='算法分类')),
                ('summary', models.CharField(blank=True, default='', help_text='最多使用200个字符，可以为空', max_length=200, null=True, verbose_name='摘要')),
                ('key_words', models.CharField(blank=True, default='Mr数据杨,CMS管理平台', help_text='填写格式：默认样式。使用,分割。最多使用100个字符', max_length=100, null=True, verbose_name='关键词')),
                ('cover_jpg', models.ImageField(blank=True, default='ArticleCover/default.png', help_text='若没有选择封面，则使用默认封面', null=True, upload_to='ArticleCover/%Y/%m', verbose_name='文章封面图片')),
                ('cover_url', models.URLField(help_text='若没有选择封面，则使用默认文章封面图片', max_length=500, verbose_name='文章封面链接')),
                ('source', models.CharField(blank=True, default='原创', help_text='最多使用50个字符，可以为空', max_length=50, null=True, verbose_name='文章来源')),
                ('source_url', models.CharField(blank=True, default='原创', help_text="若无使用默认填写'原创'即可，链接长度500个字符", max_length=500, null=True, verbose_name='原文链接')),
                ('province', models.CharField(blank=True, default='全国', help_text='最多使用20个字符，可以为空', max_length=20, verbose_name='省市区域')),
                ('city', models.CharField(blank=True, default='全地区', help_text='最多使用20个字符，可以为空', max_length=20, verbose_name='城市区域')),
                ('share_num', models.IntegerField(default=0, help_text='用户转发数', verbose_name='转发数')),
                ('read_num', models.IntegerField(default=0, help_text='用户浏览数', verbose_name='浏览数')),
                ('fav_num', models.IntegerField(default=0, help_text='用户收藏数', verbose_name='收藏数')),
                ('integral_num', models.IntegerField(default=0, help_text='购买内容需要使用积分，默认0为不需要积分', verbose_name='积分价格')),
            ],
            options={
                'verbose_name': '文章信息管理',
                'verbose_name_plural': '文章信息管理',
            },
        ),
        migrations.CreateModel(
            name='ArticleInfoHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_slug', models.SlugField(default=apps.Configuration.config_choose.default_time, verbose_name='文章slug')),
                ('position', models.CharField(default='', help_text='主页内容展示的模块名称', max_length=50, verbose_name='主页展示位置名称')),
                ('position_id', models.CharField(default='', help_text='主页内容展示的模块id', max_length=50, verbose_name='主页展示位置ID')),
                ('module_top', models.CharField(choices=[('0', '不置顶'), ('1', '置顶')], default=0, help_text='默认不置顶', max_length=1, verbose_name='文章是否置顶')),
                ('title', models.CharField(default='', help_text='最多使用50个字符', max_length=100, verbose_name='标题')),
                ('category', models.CharField(default='', help_text='最多使用50个字符', max_length=50, verbose_name='所属类别')),
                ('item', models.CharField(default='', help_text='最多使用50个字符', max_length=50, verbose_name='所属栏目')),
                ('summary', models.CharField(max_length=200, verbose_name='摘要')),
                ('share_num', models.IntegerField(default=0, verbose_name='转发数')),
                ('read_num', models.IntegerField(default=0, verbose_name='浏览数')),
                ('fav_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('integral_num', models.IntegerField(default=0, verbose_name='积分价格')),
                ('cover_jpg', models.ImageField(blank=True, null=True, upload_to='', verbose_name='文章封面图片')),
                ('cover_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='文章封面链接')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='使用默认的系统时间', verbose_name='数据创建时间')),
            ],
            options={
                'verbose_name': '主页数据管理',
                'verbose_name_plural': '主页数据管理',
            },
        ),
        migrations.CreateModel(
            name='ArticleInfoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_slug', models.SlugField(default=apps.Configuration.config_choose.default_time, verbose_name='文章slug')),
                ('title', models.CharField(default='', help_text='最多使用50个字符', max_length=100, verbose_name='标题')),
                ('category', models.CharField(default='', help_text='最多使用50个字符', max_length=50, verbose_name='所属类别')),
                ('item', models.CharField(default='', help_text='最多使用50个字符', max_length=50, verbose_name='所属栏目')),
                ('summary', models.CharField(max_length=200, verbose_name='摘要')),
                ('share_num', models.IntegerField(default=0, verbose_name='转发数')),
                ('read_num', models.IntegerField(default=0, verbose_name='浏览数')),
                ('fav_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('integral_num', models.IntegerField(default=0, verbose_name='积分价格')),
                ('cover_jpg', models.ImageField(blank=True, null=True, upload_to='', verbose_name='文章封面图片')),
                ('cover_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='文章封面链接')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='使用默认的系统时间', verbose_name='数据创建时间')),
            ],
            options={
                'verbose_name': '栏目数据管理',
                'verbose_name_plural': '栏目数据管理',
            },
        ),
        migrations.CreateModel(
            name='ArticleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', '未审核'), ('1', '已审核'), ('2', '审核不通过')], default=1, help_text='默认未审核', max_length=1, verbose_name='使用状态')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='使用默认的系统时间', verbose_name='数据创建时间')),
                ('name', models.CharField(help_text='最多使用30个字符', max_length=30, verbose_name='栏目名称')),
            ],
            options={
                'verbose_name': '文章栏目管理',
                'verbose_name_plural': '文章栏目管理',
            },
        ),
        migrations.CreateModel(
            name='ArticleStorage',
            fields=[
                ('storage_slug', models.SlugField(default=apps.Configuration.config_choose.default_time, help_text='自动按时间戳生成', primary_key=True, serialize=False, verbose_name='文章slug')),
                ('storage_content', DjangoUeditor.models.UEditorField(blank=True, default='链接失效请点击：我的文章-我的后台联系管理员', null=True, verbose_name='附件地址')),
            ],
            options={
                'verbose_name': '文章附件管理',
                'verbose_name_plural': '文章附件管理',
            },
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', '未审核'), ('1', '已审核'), ('2', '审核不通过')], default=1, help_text='默认未审核', max_length=1, verbose_name='使用状态')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='使用默认的系统时间', verbose_name='数据创建时间')),
                ('name', models.CharField(help_text='最多使用20个字符', max_length=50, verbose_name='标签名称')),
            ],
            options={
                'verbose_name': '文章标签管理',
                'verbose_name_plural': '文章标签管理',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='最大长度50个字符', max_length=50, verbose_name='Banner名称')),
                ('type', models.CharField(default='', help_text='最大长度50个字符', max_length=50, verbose_name='Banner类别')),
                ('info', models.CharField(default='', help_text='最大长度50个字符', max_length=50, verbose_name='Banner介绍')),
                ('image', models.ImageField(blank=True, help_text='像素大小1920x768', upload_to='BannerImager/%Y/%m', verbose_name='轮播图图片')),
                ('url', models.URLField(default='www.baidu.com', help_text='广告轮播图URL链接', verbose_name='轮播图链接')),
            ],
            options={
                'verbose_name': 'Banner轮播图管理',
                'verbose_name_plural': 'Banner轮播图管理',
            },
        ),
        migrations.CreateModel(
            name='ArticleEdit',
            fields=[
                ('articlestorage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='Article.ArticleStorage')),
                ('articledetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='Article.ArticleDetail')),
                ('articleinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Article.ArticleInfo')),
            ],
            options={
                'verbose_name': '新闻编辑内容',
                'verbose_name_plural': '新闻编辑内容',
            },
            bases=('Article.articleinfo', 'Article.articledetail', 'Article.articlestorage'),
        ),
    ]
