# Generated by Django 3.0.3 on 2021-12-30 14:35

import DjangoUeditor.models
import apps.Configuration.config_choose
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Article', '0002_auto_20211226_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'verbose_name': '文章一级大类管理', 'verbose_name_plural': '文章一级大类管理'},
        ),
        migrations.AlterModelOptions(
            name='articleedit',
            options={'verbose_name': '文章内容编辑', 'verbose_name_plural': '文章内容编辑'},
        ),
        migrations.AlterModelOptions(
            name='articleinfo',
            options={'verbose_name': '文章基本信息管理', 'verbose_name_plural': '文章基本信息管理'},
        ),
        migrations.AlterModelOptions(
            name='articleinfohome',
            options={'verbose_name': '主页文章数据管理', 'verbose_name_plural': '主页文章数据管理'},
        ),
        migrations.AlterModelOptions(
            name='articleinfoitem',
            options={'verbose_name': '栏目文章数据管理', 'verbose_name_plural': '栏目文章数据管理'},
        ),
        migrations.AlterModelOptions(
            name='articleitem',
            options={'verbose_name': '文章二级栏目管理', 'verbose_name_plural': '文章二级栏目管理'},
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='add_user',
            field=models.ForeignKey(help_text='数据录入系统用户', on_delete=django.db.models.deletion.CASCADE, related_name='ACAddUser', to=settings.AUTH_USER_MODEL, verbose_name='数据录入用户'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='数据创建时间，使用默认的系统时间', verbose_name='数据创建时间'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='name',
            field=models.CharField(help_text='文章一级大类名称', max_length=30, verbose_name='大类名称'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='status',
            field=models.CharField(choices=[('0', '未审核'), ('1', '已审核'), ('2', '审核不通过')], default=0, help_text='使用状态，默认未审核', max_length=1, verbose_name='使用状态'),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='文章正文'),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='detail_slug',
            field=models.SlugField(default=apps.Configuration.config_choose.default_time, help_text='slug按照时间戳自动生成', primary_key=True, serialize=False, verbose_name='文章slug标签'),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='ai_type',
            field=models.CharField(blank=True, help_text='算法API接口的文章分类', max_length=20, null=True, verbose_name='算法分类'),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='article_author',
            field=models.ForeignKey(help_text='数据录入系统用户', on_delete=django.db.models.deletion.CASCADE, related_name='AIAuthor', to=settings.AUTH_USER_MODEL, verbose_name='文章作者'),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='audit_user',
            field=models.ForeignKey(blank=True, help_text='数据录入系统用户', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AIAudit', to=settings.AUTH_USER_MODEL, verbose_name='审核用户'),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='category',
            field=models.ForeignKey(help_text='文章所属的一级大类', on_delete=django.db.models.deletion.CASCADE, related_name='ArticleInfoCategory', to='Article.ArticleCategory', verbose_name='文章一级类别'),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='city',
            field=models.CharField(blank=True, default='全地区', help_text='用于标记文章显示的市级区域，默认全地区', max_length=20, verbose_name='城市区域'),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='cover_jpg',
            field=models.ImageField(blank=True, default='ArticleCover/default.png', help_text='若未上传封面，则使用默认图片', null=True, upload_to='ArticleCover/%Y/%m', verbose_name='文章封面图片'),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='cover_url',
            field=models.URLField(help_text='爬虫抓取的文章原文封面url链接', max_length=500, verbose_name='文章封面链接'),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='数据创建时间，使用默认的系统时间', verbose_name='数据创建时间'),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='fav_num',
            field=models.IntegerField(default=0, help_text='用户收藏文章数量', verbose_name='文章收藏数'),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='home_position',
            field=models.CharField(choices=[('0', '非首页显示'), ('1', '最新内容'), ('2', '热门内容'), ('3', '浏览最多'), ('4', '转发最多'), ('5', '收藏最多'), ('6', '内容滚动推荐'), ('7', '大图置顶轮播')], default=0, help_text='默认非主页显示，若没有请在config_choose中添加', max_length=1, verbose_name='文章显示位置'),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='info_slug',
            field=models.SlugField(default=apps.Configuration.config_choose.default_time, help_text='slug按照时间戳自动生成', primary_key=True, serialize=False, verbose_name='文章slug标签'),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='integral_num',
            field=models.IntegerField(default=0, help_text='阅读文章需要的积分数量，默认0', verbose_name='文章积分'),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='item',
            field=models.ForeignKey(help_text='文章所属的二级栏目', on_delete=django.db.models.deletion.CASCADE, related_name='ArticleInfoItem', to='Article.ArticleItem', verbose_name='文章二级栏目'),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='item_position',
            field=models.CharField(choices=[('0', '栏目中不显示'), ('1', '栏目中显示数据')], default=0, help_text='默认栏目中不显示', max_length=1, verbose_name='栏目是否可见'),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='key_words',
            field=models.CharField(blank=True, default='Mr数据杨,CMS管理平台', help_text='文章关键词，格式：默认样式。使用,分割。最多使用100个字符', max_length=100, null=True, verbose_name='关键词'),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='province',
            field=models.CharField(blank=True, default='全国', help_text='用于标记文章显示的省级区域，默认全国', max_length=20, verbose_name='省市区域'),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='read_num',
            field=models.IntegerField(default=0, help_text='用户浏览文章数量', verbose_name='文章浏览数'),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='share_num',
            field=models.IntegerField(default=0, help_text='用户转发文章数量', verbose_name='文章转发数'),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='source',
            field=models.CharField(blank=True, default='原创', help_text='爬虫抓取的文章来源网站信息，若不存在则标记未原创', max_length=50, null=True, verbose_name='原文来源网站'),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='source_url',
            field=models.CharField(blank=True, default='原创', help_text='爬虫抓取的文章来源的url链接，若不存在则标记未原创', max_length=500, null=True, verbose_name='原文来源链接'),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='status',
            field=models.CharField(choices=[('0', '未审核'), ('1', '已审核'), ('2', '审核不通过')], default=0, help_text='默认未审核，超级用户和编辑有权限审核', max_length=1, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='summary',
            field=models.CharField(blank=True, default='', help_text='文章标题，最多使用200个字符', max_length=200, null=True, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='文章标签中文名称', related_name='ArticleInfoTags', to='Article.ArticleTag', verbose_name='文章中文标签'),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='title',
            field=models.CharField(default='', help_text='文章标题，最多使用100个字符', max_length=100, verbose_name='文章标题'),
        ),
        migrations.AlterField(
            model_name='articleinfohome',
            name='category',
            field=models.CharField(default='', help_text='文章所属的一级大类', max_length=50, verbose_name='文章一级类别'),
        ),
        migrations.AlterField(
            model_name='articleinfohome',
            name='cover_jpg',
            field=models.ImageField(blank=True, help_text='若未上传封面，则使用默认图片', null=True, upload_to='', verbose_name='文章封面图片'),
        ),
        migrations.AlterField(
            model_name='articleinfohome',
            name='cover_url',
            field=models.URLField(blank=True, help_text='爬虫抓取的文章原文封面url链接', max_length=500, null=True, verbose_name='文章封面链接'),
        ),
        migrations.AlterField(
            model_name='articleinfohome',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='数据创建时间，使用默认的系统时间', verbose_name='数据创建时间'),
        ),
        migrations.AlterField(
            model_name='articleinfohome',
            name='fav_num',
            field=models.IntegerField(default=0, help_text='用户收藏文章数量', verbose_name='文章收藏数'),
        ),
        migrations.AlterField(
            model_name='articleinfohome',
            name='integral_num',
            field=models.IntegerField(default=0, help_text='阅读文章需要的积分数量，默认0', verbose_name='文章积分'),
        ),
        migrations.AlterField(
            model_name='articleinfohome',
            name='item',
            field=models.CharField(default='', help_text='文章所属的二级栏目', max_length=50, verbose_name='文章二级栏目'),
        ),
        migrations.AlterField(
            model_name='articleinfohome',
            name='module_top',
            field=models.CharField(choices=[('0', '不置顶'), ('1', '置顶')], default=0, help_text='文章是否所在位置置顶，默认不置顶', max_length=1, verbose_name='文章置顶标识'),
        ),
        migrations.AlterField(
            model_name='articleinfohome',
            name='position',
            field=models.CharField(default='', help_text='主页展示位置名称', max_length=50, verbose_name='主页展示位置名称'),
        ),
        migrations.AlterField(
            model_name='articleinfohome',
            name='position_id',
            field=models.CharField(default='', help_text='主页展示位置ID编号', max_length=50, verbose_name='主页展示位置ID'),
        ),
        migrations.AlterField(
            model_name='articleinfohome',
            name='read_num',
            field=models.IntegerField(default=0, help_text='用户浏览文章数量', verbose_name='文章浏览数'),
        ),
        migrations.AlterField(
            model_name='articleinfohome',
            name='share_num',
            field=models.IntegerField(default=0, help_text='用户转发文章数量', verbose_name='文章转发数'),
        ),
        migrations.AlterField(
            model_name='articleinfohome',
            name='summary',
            field=models.CharField(help_text='文章标题，最多使用200个字符', max_length=200, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='articleinfohome',
            name='title',
            field=models.CharField(default='', help_text='文章标题，最多使用100个字符', max_length=100, verbose_name='文章标题'),
        ),
        migrations.AlterField(
            model_name='articleinfoitem',
            name='category',
            field=models.CharField(default='', help_text='文章所属的一级大类', max_length=50, verbose_name='文章一级类别'),
        ),
        migrations.AlterField(
            model_name='articleinfoitem',
            name='cover_jpg',
            field=models.ImageField(blank=True, help_text='若未上传封面，则使用默认图片', null=True, upload_to='', verbose_name='文章封面图片'),
        ),
        migrations.AlterField(
            model_name='articleinfoitem',
            name='cover_url',
            field=models.URLField(blank=True, help_text='爬虫抓取的文章原文封面url链接', max_length=500, null=True, verbose_name='文章封面链接'),
        ),
        migrations.AlterField(
            model_name='articleinfoitem',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='数据创建时间，使用默认的系统时间', verbose_name='数据创建时间'),
        ),
        migrations.AlterField(
            model_name='articleinfoitem',
            name='fav_num',
            field=models.IntegerField(default=0, help_text='用户收藏文章数量', verbose_name='文章收藏数'),
        ),
        migrations.AlterField(
            model_name='articleinfoitem',
            name='info_slug',
            field=models.SlugField(default=apps.Configuration.config_choose.default_time, help_text='slug按照时间戳自动生成', verbose_name='文章slug标签'),
        ),
        migrations.AlterField(
            model_name='articleinfoitem',
            name='integral_num',
            field=models.IntegerField(default=0, help_text='阅读文章需要的积分数量，默认0', verbose_name='文章积分'),
        ),
        migrations.AlterField(
            model_name='articleinfoitem',
            name='item',
            field=models.CharField(default='', help_text='文章所属的二级栏目', max_length=50, verbose_name='文章二级栏目'),
        ),
        migrations.AlterField(
            model_name='articleinfoitem',
            name='read_num',
            field=models.IntegerField(default=0, help_text='用户浏览文章数量', verbose_name='文章浏览数'),
        ),
        migrations.AlterField(
            model_name='articleinfoitem',
            name='share_num',
            field=models.IntegerField(default=0, help_text='用户转发文章数量', verbose_name='文章转发数'),
        ),
        migrations.AlterField(
            model_name='articleinfoitem',
            name='summary',
            field=models.CharField(help_text='文章标题，最多使用200个字符', max_length=200, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='articleinfoitem',
            name='title',
            field=models.CharField(default='', help_text='文章标题，最多使用100个字符', max_length=100, verbose_name='文章标题'),
        ),
        migrations.AlterField(
            model_name='articleitem',
            name='add_user',
            field=models.ForeignKey(help_text='数据录入系统用户', on_delete=django.db.models.deletion.CASCADE, related_name='AIAddUser', to=settings.AUTH_USER_MODEL, verbose_name='数据录入用户'),
        ),
        migrations.AlterField(
            model_name='articleitem',
            name='category',
            field=models.ForeignKey(help_text='栏目所属一级大类，若没有请在文章类别管理中创建', on_delete=django.db.models.deletion.CASCADE, related_name='ArticleItemCategory', to='Article.ArticleCategory', verbose_name='栏目所属一级大类'),
        ),
        migrations.AlterField(
            model_name='articleitem',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='数据创建时间，使用默认的系统时间', verbose_name='数据创建时间'),
        ),
        migrations.AlterField(
            model_name='articleitem',
            name='name',
            field=models.CharField(help_text='文章二级栏目名称', max_length=30, verbose_name='栏目名称'),
        ),
        migrations.AlterField(
            model_name='articleitem',
            name='status',
            field=models.CharField(choices=[('0', '未审核'), ('1', '已审核'), ('2', '审核不通过')], default=0, help_text='使用状态，默认未审核', max_length=1, verbose_name='使用状态'),
        ),
        migrations.AlterField(
            model_name='articlestorage',
            name='storage_content',
            field=DjangoUeditor.models.UEditorField(blank=True, default='链接失效请点击：我的文章-我的后台联系管理员', null=True, verbose_name='文章附件信息'),
        ),
        migrations.AlterField(
            model_name='articlestorage',
            name='storage_slug',
            field=models.SlugField(default=apps.Configuration.config_choose.default_time, help_text='slug按照时间戳自动生成', primary_key=True, serialize=False, verbose_name='文章slug标签'),
        ),
        migrations.AlterField(
            model_name='articletag',
            name='add_user',
            field=models.ForeignKey(help_text='数据录入系统用户', on_delete=django.db.models.deletion.CASCADE, related_name='ATAddUser', to=settings.AUTH_USER_MODEL, verbose_name='数据录入用户'),
        ),
        migrations.AlterField(
            model_name='articletag',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='数据创建时间，使用默认的系统时间', verbose_name='数据创建时间'),
        ),
        migrations.AlterField(
            model_name='articletag',
            name='name',
            field=models.CharField(help_text='文章标签中文名称', max_length=50, verbose_name='标签名称'),
        ),
        migrations.AlterField(
            model_name='articletag',
            name='status',
            field=models.CharField(choices=[('0', '未审核'), ('1', '已审核'), ('2', '审核不通过')], default=0, help_text='使用状态，默认未审核', max_length=1, verbose_name='使用状态'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, help_text='轮播图像素大小1920x768', upload_to='BannerImager/%Y/%m', verbose_name='轮播图图片'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='info',
            field=models.CharField(default='', help_text='轮播图文字介绍', max_length=50, verbose_name='Banner介绍'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='name',
            field=models.CharField(default='', help_text='轮播图名称', max_length=50, verbose_name='Banner名称'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='type',
            field=models.CharField(default='', help_text='轮播图类别', max_length=50, verbose_name='Banner类别'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.URLField(default='www.baidu.com', help_text='轮播图点击跳转url链接', verbose_name='轮播图链接'),
        ),
    ]
